using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using FluentAssertions;
using TaxCompliance.Application.Auth;
using TaxCompliance.Application.Common;
using TaxCompliance.Application.ComplianceTaskOccurrences;
using TaxCompliance.Application.ComplianceTaskRules;
using TaxCompliance.Application.ComplianceTemplates;
using TaxCompliance.Application.Jurisdictions;
using TaxCompliance.Application.LegalEntities;
using TaxCompliance.Application.Organizations;
using TaxCompliance.Domain.Enums;

namespace TaxCompliance.Tests.Integration;

public class WorkflowSmokeIntegrationTests : IClassFixture<TaxComplianceApiFactory>
{
    private readonly TaxComplianceApiFactory factory;

    public WorkflowSmokeIntegrationTests(TaxComplianceApiFactory factory)
    {
        this.factory = factory;
    }

    [Fact]
    public async Task SmokeFlow_ShouldLoginCreateOrgRuleGenerateOccurrenceAndCompleteTask()
    {
        using var client = factory.CreateClient();
        var token = await GetAccessTokenAsync(client);
        client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

        var organizationResponse = await client.PostAsJsonAsync("/api/organizations", new SaveOrganizationRequest
        {
            Name = "Smoke Test Org",
            Code = "SMOKE",
            Description = "E2E smoke organization",
            IsActive = true
        });
        organizationResponse.StatusCode.Should().Be(HttpStatusCode.Created);
        var organization = await organizationResponse.Content.ReadFromJsonAsync<OrganizationDetailDto>();
        client.DefaultRequestHeaders.Add(OrganizationContextHeaders.OrganizationId, organization!.Id.ToString());

        var jurisdictionResponse = await client.PostAsJsonAsync("/api/jurisdictions", new SaveJurisdictionRequest
        {
            Name = "Smoke Jurisdiction",
            CountryCode = "US",
            RegionCode = "CA",
            FilingAuthority = "California FTB",
            IsActive = true
        });
        jurisdictionResponse.StatusCode.Should().Be(HttpStatusCode.Created);
        var jurisdiction = await jurisdictionResponse.Content.ReadFromJsonAsync<JurisdictionDetailDto>();

        var templateResponse = await client.PostAsJsonAsync("/api/compliance-templates", new SaveComplianceTemplateRequest
        {
            Name = "Smoke VAT Template",
            FilingType = "VAT",
            Description = "Smoke template",
            ReminderDaysBeforeDue = 7,
            IsActive = true
        });
        templateResponse.StatusCode.Should().Be(HttpStatusCode.Created);
        var template = await templateResponse.Content.ReadFromJsonAsync<ComplianceTemplateDetailDto>();

        var legalEntityResponse = await client.PostAsJsonAsync("/api/legal-entities", new SaveLegalEntityRequest
        {
            OrganizationId = organization!.Id,
            Name = "Smoke Legal Entity",
            RegistrationNumber = "SMOKE-REG-1",
            TaxIdentifier = "SMOKE-TAX-1",
            IsActive = true
        });
        legalEntityResponse.StatusCode.Should().Be(HttpStatusCode.Created);
        var legalEntity = await legalEntityResponse.Content.ReadFromJsonAsync<LegalEntityDetailDto>();

        var ruleResponse = await client.PostAsJsonAsync("/api/compliance-task-rules", new SaveComplianceTaskRuleRequest
        {
            LegalEntityId = legalEntity!.Id,
            JurisdictionId = jurisdiction!.Id,
            ComplianceTemplateId = template!.Id,
            Title = "Smoke Monthly Rule",
            Description = "Generated by smoke test",
            RecurrenceType = RecurrenceType.Monthly,
            DueDayOfMonth = 15,
            IsActive = true
        });
        ruleResponse.StatusCode.Should().Be(HttpStatusCode.Created);

        var generateResponse = await client.PostAsync("/api/compliance-task-occurrences/generate", null);
        generateResponse.StatusCode.Should().Be(HttpStatusCode.OK);

        var occurrencesResponse = await client.GetAsync("/api/compliance-task-occurrences?page=1&pageSize=10");
        occurrencesResponse.StatusCode.Should().Be(HttpStatusCode.OK);
        var occurrences = await occurrencesResponse.Content.ReadFromJsonAsync<PagedResult<ComplianceTaskOccurrenceListItemDto>>();
        occurrences!.Items.Should().NotBeEmpty();

        var occurrence = occurrences.Items.First();
        var statusResponse = await client.PostAsJsonAsync(
            $"/api/compliance-task-occurrences/{occurrence.Id}/status",
            new UpdateTaskOccurrenceStatusRequest { Status = ComplianceTaskOccurrenceStatus.Completed });
        statusResponse.StatusCode.Should().Be(HttpStatusCode.OK);
        var completed = await statusResponse.Content.ReadFromJsonAsync<ComplianceTaskOccurrenceDetailDto>();
        completed!.Status.Should().Be(ComplianceTaskOccurrenceStatus.Completed);
    }

    private static async Task<string> GetAccessTokenAsync(HttpClient client)
    {
        var response = await client.PostAsJsonAsync("/api/auth/login", new LoginRequest
        {
            Email = "admin@taxplatform.local",
            Password = "Admin123!"
        });

        var payload = await response.Content.ReadFromJsonAsync<ApiResponse<LoginResponse>>();
        return payload?.Data?.AccessToken ?? string.Empty;
    }
}
